In [20]:
import numpy as np

In [23]:
list_ = [ '1' , '2' , '3' ,'4' , '5' ]
array_list = np.array(object = list_)

1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

> yes, there's a difference between the data type of list_ and array_list variables. 
* list_ is a python list, while array_list is a Numpy array.

In [8]:
print(f"The data type of {list_} is : {type(list_)}")
print(f"The data type of {array_list} is : {type(array_list)}")

The data type of ['1', '2', '3', '4', '5'] is : <class 'list'>
The data type of ['1' '2' '3' '4' '5'] is : <class 'numpy.ndarray'>


2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [13]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
for i in array_list :
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


3. Considering the following changes in the variable, array_list: 
* array_list = np.array(object = list_, dtype = int)
> Will there be any difference in the data type of the elements present in both the variables, list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and array_list

In [26]:
array_list = np.array(object = list_, dtype = int)

In [27]:
array_list.dtype

dtype('int64')

In [24]:
for i in list_ :
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [28]:
for i in array_list :
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


> the data type of the elements in the list_ doesn't change and remain "str", because the list_ itself isn't modified. 
>> while , the datatype of the array_list are converted to "numpy.int64" - this is because of creating the array_list with dtype parameter as int.  
* hence the elements in the array_list are converted to integers.

4.  Consider the following code to answer the below : 
* num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
* num_array = np.array(object = num_list)
> Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

In [31]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(num_list)

In [32]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
print(f"The shape of {num_array} is {num_array.shape }")
print(f"The size of {num_array} is {num_array.size}")

The shape of [[1 2 3]
 [4 5 6]] is (2, 3)
The size of [[1 2 3]
 [4 5 6]] is 6


5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [41]:
zeroes_array = np.array([[0,0,0],
          [0,0,0],
          [0,0,0]])
zeroes_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

6. Create an identity matrix of shape (5,5) using numpy functions?

In [46]:
identity_matrix = np.eye(5,5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])